Added support for building Android x86_64 (for ChromeOS).
Unity-Technologies/curl pull request #13
Opened 2020-11-06 22:56 UTC by monroeberg

Added support for building Android x86_64 (for ChromeOS).

2020-11-07 02:47 UTC, davidrogers-unity requested changes
Just two small changes but otherwise lgtm

2020-11-07 02:47 UTC, davidrogers-unity commented on lib/config-android-x86.h
> +#define OS "x86-unknown-linux-gnu"
I think this should be i686

2020-11-07 02:47 UTC, davidrogers-unity commented on lib/config-android-x86_64.h
> +#define OS "x86-unknown-linux-gnu"
x86_64 here

2020-11-07 05:47 UTC, monroeberg commented on lib/config-android-x86.h
> +#define OS "x86-unknown-linux-gnu"
Fixed.

2020-11-07 05:47 UTC, monroeberg commented on lib/config-android-x86_64.h
> +#define OS "x86-unknown-linux-gnu"
Fixed.

2020-11-10 08:35 UTC, aurimasc approved these changes

2020-11-10 21:23 UTC, davidrogers-unity approved these changes

2020-11-10 22:23 UTC, merged